<script type="text/javascript">
    function changeOrder(productId, delta)
    {
        var ajaxBlockUrl = '<?php echo $this->getUrl('*/productDnD/ajaxBlock', array('_current' => true)) ?>';
        new Ajax.Request(ajaxBlockUrl, {
            parameters: {
                productId: productId,
                delta: delta,
                isAjax: 'true',
                form_key: FORM_KEY
            }
        });
    }
</script>