<script type="text/javascript">
    document.observe("dom:loaded", function()
    {
        $('catalog_category_products_table').down('tbody').setAttribute('id', 'catalog_category_products_table_tbody');
        Sortable.create("catalog_category_products_table_tbody", { tag: "tr" });
    });

    function changeOrder() {
        var ajaxBlockUrl = '<?php echo $this->getUrl('*/hackathon_productdnd/ajaxBlock', array('_current' => true)) ?>';
        new Ajax.Request(ajaxBlockUrl, {
            parameters: {
                project_id: projectObj.value,
                isAjax: 'true',
                form_key: FORM_KEY
            },
            onSuccess: function(transport) {
                try {
                    if (transport.responseText.isJSON()) {
                        var response = transport.responseText.evalJSON();
                        if (response.error) {
                            alert(response.message);
                        }
                        if(response.ajaxExpired && response.ajaxRedirect) {
                            setLocation(response.ajaxRedirect);
                        }
                    } else {
                        alert(transport.responseText);
                    }
                }
                catch (e) {
                    alert(transport.responseText);
                }
            }
        });
    }
</script>

