<script type="text/javascript">
        $('catalog_category_products_table').down('tbody').setAttribute('id', 'catalog_category_products_table_tbody');

        var listId = 'catalog_category_products_table_tbody';
        var listTag = 'tr';
        var ajaxUrl = '<?php echo $this->getUrl('*/productDnD/ajaxBlock', array('_current' => true)) ?>';

        resetListItems(listId, listTag);
        processSorting(listId, listTag, ajaxUrl);
</script>

